# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform YOURLS installation tasks
  tags:
    - setup-all
    - setup-yourls
    - install-all
    - install-yourls
  block:
    - name: Validate YOURLS configuration
      when: yourls_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install YOURLS
      when: yourls_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform YOURLS uninstallation tasks
  tags:
    - setup-all
    - setup-yourls
  block:
    - name: Uninstall YOURLS
      when: not yourls_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
